### ISSUE TITLE
No local broadcast with Share

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip-Experimental#180] opened 2015-11-22 16:34 UTC
Bug report via chat with @KeesaKat / Marybeth: 
1. xDrip doesn't broadcast to NightWatch (and HAPP), if the value is not calculated ("???").
   That would be good to have as NightWatch in recent versions can show raw values as well.
2. The local broadcast does not broadcast raw but copies the value if  used with a share receiver.

**Comment by Entropy512** [comment] 2015-12-06 16:01
OK, number 2 explains what I've been seeing since moving to the latest NightWatch, I can confirm that the raw values are always identical to the "filtered" value

**Comment by AdrianLxM** [comment] 2015-12-18 02:55
@KeesaKat, @Entropy512: This PR should solve the issue: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/223

Would you like to test it?

**Comment by AdrianLxM** [comment] 2015-12-25 00:52
#223 was also a fix for this issue.

**Closed as completed** 2015-12-25 00:51 UTC
