### ISSUE TITLE
Import Fails on Marshmallow and above

### ISSUE THREAD

**Issue by TecMunky** [StephenBlackWasAlreadyTaken/xDrip-Experimental#370] opened 2016-07-31 06:21 UTC
The xDrip app crashes on Marshmallow when importing settings, and fails to import database.

I have tried this on 3 phones:
LG-G2 (5.0.2) 
- can import settings and database with no issues

Nexus 5X (6.0.1) or Nexus 6P (Android N Preview #5)
- importing database results in absolutely no data
- importing settings crashes the app

I get "xDrip has stopped" when I try to import settings on the 5X and 6P.  When the app crashes - the only way to recover is to uninstall the app, reboot the phone, and install it again.

I get no data records at all when I try to import database on the 5X and 6P.  Exporting data from the 6P (my daily driver) and importing on the LG-G2 results in all the data records showing up in the app.

I think this might have something to do with different permissions using Android 6.x and above.

I am willing to track this down - but I would need to know where to look

**Comment by tzachi-dar** [comment] 2016-07-31 15:07
Thanks for reporting this.
As for settings, what the restore does is copy the settings and then kill the process.
What should happen is that once the process is opened again, you should see new settings.

In any case to debug this things, you need to execute the scenarios and later run:
adb logcat -v time > file
and post the file here.
Hopefully it will show what the problem here.
If you are using android studio, than it can collect the logs even without running anything in the command line.

**Comment by tzachi-dar** [comment] 2016-08-02 20:29
Seems that the problem is in here: https://fabric.io/yoursolaces-projects/android/apps/com.eveningoutpost.dexdrip/issues/5750aa0effcdc04250beaa31

Solutions seems to be here: https://github.com/google/gson/issues/648

I should be getting an android 6.0 device tomorrow, so hope to solve this soon.

**Comment by tzachi-dar** [comment] 2016-08-04 21:05
This should be fixed now. Tried this with nexus5x.
Both imports work.

Please make sure that you have given access to the storage to xDrip.

**Comment by TecMunky** [comment] 2016-08-04 21:08
Could you provide a summary of the problem and the solution. I couldn't see
your link to the fabric site, because I would have to be part of your
"team" to see it (according to the guys at fabric).

Also, is the fix on the g5-beta branch on github?

**Comment by tzachi-dar** [comment] 2016-08-04 21:13
Fix is here: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/372

Crash log is here:
java.lang.RuntimeException: Unable to create application com.eveningoutpost.dexdrip.xdrip: java.lang.SecurityException: Can't make field constructor accessible

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4715)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.app.ActivityThread.-wrap1(ActivityThread.java)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.os.Handler.dispatchMessage(Handler.java:102)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.os.Looper.loop(Looper.java:148)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.app.ActivityThread.main(ActivityThread.java:5422)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at java.lang.reflect.Method.invoke(Native Method)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

08-04 00:14:32.400 E/AndroidRuntime( 1001): Caused by: java.lang.SecurityException: Can't make field constructor accessible

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at java.lang.reflect.Constructor.setAccessible(Constructor.java:334)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:101)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:83)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:99)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.MapTypeAdapterFactory.getKeyAdapter(MapTypeAdapterFactory.java:142)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:125)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.fromJson(Gson.java:886)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.fromJson(Gson.java:852)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.fromJson(Gson.java:801)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.google.gson.Gson.fromJson(Gson.java:773)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.eveningoutpost.dexdrip.Models.AlertType.fromSettings(AlertType.java:588)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at com.eveningoutpost.dexdrip.xdrip.onCreate(xdrip.java:36)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)

08-04 00:14:32.400 E/AndroidRuntime( 1001):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)

Fix is only at master, hopefully, the g5 beta will be merged to master.

**Comment by TecMunky** [comment] 2016-08-07 00:31
I tested this by making the changes for #372 to my copy of the g5-beta
branch.

Importing settings now works great.

However, importing the database still imports nothing.

On Aug 4, 2016 16:13, "tzachi-dar" notifications@github.com wrote:

Fix is here: #372
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/372

Crash log is here:
java.lang.RuntimeException: Unable to create application
com.eveningoutpost.dexdrip.xdrip: java.lang.SecurityException: Can't make
field constructor accessible

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.app.ActivityThread.
handleBindApplication(ActivityThread.java:4715)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.app.ActivityThread.-
wrap1(ActivityThread.java)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.app.ActivityThread$H.
handleMessage(ActivityThread.java:1405)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.os.Handler.
dispatchMessage(Handler.java:102)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
android.os.Looper.loop(Looper.java:148)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.app.ActivityThread.
main(ActivityThread.java:5422)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
java.lang.reflect.Method.invoke(Native
Method)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.android.internal.os.
ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.android.internal.os.
ZygoteInit.main(ZygoteInit.java:616)

08-04 00:14:32.400 E/AndroidRuntime( 1001): Caused by:
java.lang.SecurityException: Can't make field constructor accessible

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
java.lang.reflect.Constructor.setAccessible(Constructor.java:334)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.internal.
ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:
101)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.internal.
ConstructorConstructor.get(ConstructorConstructor.java:83)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(
ReflectiveTypeAdapterFactory.java:99)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.Gson.
getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.MapTypeAdapterFactory.getKeyAdapter(
MapTypeAdapterFactory.java:142)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.MapTypeAdapterFactory.create(
MapTypeAdapterFactory.java:125)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.Gson.
getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(
ReflectiveTypeAdapterFactory.java:115)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(
ReflectiveTypeAdapterFactory.java:164)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(
ReflectiveTypeAdapterFactory.java:100)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.Gson.
getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(
ReflectiveTypeAdapterFactory.java:115)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(
ReflectiveTypeAdapterFactory.java:164)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(
ReflectiveTypeAdapterFactory.java:100)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.Gson.
getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.internal.bind.ArrayTypeAdapter$1.create(
ArrayTypeAdapter.java:48)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.google.gson.Gson.
getAdapter(Gson.java:423)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.Gson.fromJson(Gson.java:886)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.Gson.fromJson(Gson.java:852)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.Gson.fromJson(Gson.java:801)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at
com.google.gson.Gson.fromJson(Gson.java:773)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.eveningoutpost.dexdrip.
Models.AlertType.fromSettings(AlertType.java:588)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at com.eveningoutpost.dexdrip.
xdrip.onCreate(xdrip.java:36)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.app.Instrumentation.
callApplicationOnCreate(Instrumentation.java:1013)

08-04 00:14:32.400 E/AndroidRuntime( 1001): at android.app.ActivityThread.
handleBindApplication(ActivityThread.java:4712)

Fix is only at master, hopefully, the g5 beta will be merged to master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/issues/370#issuecomment-237685258,
or mute the thread

**Comment by TecMunky** [comment] 2016-08-07 01:22
One more thing. When we get database import working, I want to be able to
import all the data I've exported to database files. To do that I need some
guidance on how to merge multiple dataset files into one file.

I can view the data in any one database, but am not sure how to merge them.
Additionally, the timestamp for each entry is confusing, as I don't know
how to convert the value to a date and time.

Thanks.
Jim

**Comment by tzachi-dar** [comment] 2016-08-07 02:46
Timestamps is milliseconds from epoch. http://www.epochconverter.com/

Merging databases can be done externally. See for example:
http://stackoverflow.com/questions/80801/how-can-i-merge-many-sqlite-databases
http://stackoverflow.com/questions/9349659/fastest-way-merge-two-sqlite-databases

Importing did seem to work on my phone, so I'll look into it a little more, but this will take me a few more days.

**Comment by TecMunky** [comment] 2016-08-07 02:55
Thanks. I am in no hurry. I tried this on the 5x. I cleared all data,
uninstalled, rebooted, installed, exported data and settings from my 6p,
transferred these to the 5x, extracted database, imported settings,
imported database. Settings works flawlessly. Database import leaves no
data, and error log shows as in attached pic.

**Comment by tzachi-dar** [comment] 2016-08-07 05:41
Can you please attach the picture again?

**Comment by TecMunky** [comment] 2016-08-07 16:20
I think the difference may be that you tested with the master branch, while
I tested with the g5-beta branch.  Some difference between these two
branches is the cause of not being able to import a database.

**Comment by TecMunky** [comment] 2016-08-07 23:40
The Crash is definitely fixed.  I just had an "opportunity" to test that.
When I rebooted my daily driver (the Nexus 6P), the xDrip app crashed on
startup.  Before when this would happen, the only option was to clear
memory, uninstall, reboot, re-install, and start from scratch again.

This time, I installed my latest build (with crash fix) over the previous
build, and xDrip came up with all my previous data still intact.

So now this is tested on the Nexus 5X on marshmallow, and on Nexus 6P with
Android N Preview (Nougat)

**Comment by TecMunky** [comment] 2016-08-07 23:50
I am looking at the code differences and I can't tell which code file is
responsible for importing the database.  I was thinking I might be able to
spot the trouble with database import.

Where should I look?

**Comment by tzachi-dar** [comment] 2016-08-08 04:31
Hi, Start by looking from DatabaseUtil.loadSql()

But I would start by loading the latest experimental build and making sure that backup/restore works there. There is a great chance that the problem is not version dependent but happens because of some other thing.

**Comment by tzachi-dar** [comment] 2016-08-28 21:08
Closing issue. Please reopen if it is still not solved.

**Closed as completed by tzachi-dar** 2016-08-28 21:08 UTC

**Comment by TecMunky** [comment] 2016-08-29 01:55
The crash was fixed.  But I am still not able to import a database.
Should I open a separate issue for this?

**Comment by tzachi-dar** [comment] 2016-08-29 07:48
Hi,

Please open a new case for import failures.
If possible, can you please add logcat logs of the failures.

Thanks
Tzachi

**Comment by vyguera** [comment] 2016-09-09 07:24
I was facing the same problem on my class Campaign containing a non annotated List field. Workaround didn't worked for me with gson 2.7, neither adding 
builder.excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC);
nor 
excludeFieldsWithoutExposeAnnotation()

I mean, the exception dissappeared, but I got a new NullPointerException after that when I tried to use gson.toJson(). on a class containing a list of campaigns and either not annotated.

As the problem is with fields without expose annotation, my workaround was simply to add @SerializedName with a name I will never use to the List field on Campaign class.

Hope this helps someone,
Greetings.
